### ISSUE TITLE
Uncaught Error with parseColor using OKLCH color format in Next.js

### ISSUE THREAD

**Issue by shing100** [disqus/disqus-react#153]
Hello,

I'm currently developing a project using Next.js and encountered an issue with parsing colors in the OKLCH format. The exact error message I received is:

```
Uncaught Error: parseColor received unparseable color: oklch(0.3551920.032071262.989)
    at VM6957 embed.js:49:9245
    at j (VM6957 embed.js:49:10631)
    at k (VM6957 embed.js:49:10790)
    at Object.m [as getAnchorColor] (VM6957 embed.js:49:11113)
    at i.toJSON (VM6957 embed.js:49:15415)
    at c.loadEmbed [as _loadEmbed] (VM6957 embed.js:51:11455)
    at VM6957 embed.js:51:15686
```

my code is:
```
import {DiscussionEmbed} from "disqus-react";

export default function LocationSalaryStat() {
    return (
        <div className="min-h-screen p-8">
            <h2 className="text-3xl font-bold mb-8 text-center">location</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {locationData.map((location) => (
                    <LocationCard key={location.name} location={location} />
                ))}
            </div>
            <DiscussionEmbed
                key={"light"}
                shortname='insight-jov'
                config={
                    {
                        url: "http://localhost:3000/salary/location",
                        identifier: "industry",
                        title: "location",
                        language: 'ko',
                    }
                }
            />
        </div>
    );
}
```
I've checked the color value format and it seems to be correct according to the OKLCH color specification. However, the parser seems unable to recognize or parse this format correctly.

Has anyone encountered a similar issue or does anyone know why this specific color format is causing an error? I'm wondering if there's a specific library or plugin that I need to use to support OKLCH color parsing in Next.js, or if there's a workaround for this issue.

Any advice or suggestions would be greatly appreciated. Thank you in advance for your help

Environment Details:

Next.js version: 14.1.0
Additional libraries/plugins used (if any): daisyUI 4.7.0

Looking forward to any insights or solutions from the community. Thank you!

**Comment by Priambodo-Kurniawan** [comment]
I also experienced the same issue when using Disqus + daisyUI 4.7.0, and after I investigated, the cause was found to be in that latest version of daisyUI.

The temporary solution was that I used is using **daisyUI version 3.9.4**. After I downgraded, the error disappeared, but it should be noted that some features in daisyUI 4.7.0 stopped working. In my case, it wasn't a problem because I hadn't yet used the latest components from daisyUI.

Hope this helps.

**Comment by shing100** [comment]
thank you. The daisyUI version downgrade issue has been resolved.

**Comment by Godsenal** [comment]
This issue arises from Disqus not being able to parse the background color in JavaScript code due to the lack of support for OKLCH. Since version 4 of DaisyUI, browsers that support OKLCH use it, so I am encountering the same issue. A temporary workaround to keep using version 4 while making Disqus work is to directly specify the background color as follows:

```css
:root[data-theme="light"] {
  background-color: // light bg color
  color:  // light content color
}

:root[data-theme="dark"] {
  background-color:  // dark bg color
  color:  // dark content color
}
```

**Comment by romanchelsea** [comment]
> This issue arises from Disqus not being able to parse the background color in JavaScript code due to the lack of support for OKLCH. Since version 4 of DaisyUI, browsers that support OKLCH use it, so I am encountering the same issue. A temporary workaround to keep using version 4 while making Disqus work is to directly specify the background color as follows:
> 
> ```css
> :root[data-theme="light"] {
>   background-color: // light bg color
>   color:  // light content color
> }
> 
> :root[data-theme="dark"] {
>   background-color:  // dark bg color
>   color:  // dark content color
> }
> ```

Will overriding background-color and color work? According to DaisyUI [colors](https://daisyui.com/docs/colors/), there are so many more colors that are using oklch().

**Comment by real-zephex** [comment]
> This issue arises from Disqus not being able to parse the background color in JavaScript code due to the lack of support for OKLCH. Since version 4 of DaisyUI, browsers that support OKLCH use it, so I am encountering the same issue. A temporary workaround to keep using version 4 while making Disqus work is to directly specify the background color as follows:
> 
> ```css
> :root[data-theme="light"] {
>   background-color: // light bg color
>   color:  // light content color
> }
> 
> :root[data-theme="dark"] {
>   background-color:  // dark bg color
>   color:  // dark content color
> }
> ```

It didn't work for me. Maybe, I am doing something wrong? I created a new file named styles.css and imported it into the Disqus component file. Am I doing something wrong?

**Comment by iEscapedVim** [comment]
it's been a year... why is this fix still here.. downgrading to 3.9.4 seems to be the only fix.

**Comment by diego-betto** [comment]
Possible fix for `embed.js` (I cannot find a repository/source for this file, so this is a monkey-patching-not-working-locally-dont-copy-and-paste :) ) just a suggestion for the Disqus guys. Hope this helps speed things up.



```js
/// ....
v = function(b) {
        function c(a) {
            return a.replace(/\s+/g, "").toLowerCase()
        }
        function d(a) {
            return a = a.replace(/^#([a-f0-9])([a-f0-9])([a-f0-9])$/, "#$1$1$2$2$3$3"),
            a = a.slice(1),
            {
                red: parseInt(a.slice(0, 2), 16),
                green: parseInt(a.slice(2, 4), 16),
                blue: parseInt(a.slice(4, 6), 16)
            }
        }
        function e(a) {
            var b = a.match(/^rgb\((\d+),(\d+),(\d+)\)$/);
            return {
                red: parseInt(b[1], 10),
                green: parseInt(b[2], 10),
                blue: parseInt(b[3], 10)
            }
        }
        function f(a) {
            var b = a.match(/^rgba\((\d+),(\d+),(\d+),([\d.]+)\)$/);
            return {
                red: parseInt(b[1], 10),
                green: parseInt(b[2], 10),
                blue: parseInt(b[3], 10),
                alpha: parseFloat(b[4])
            }
        }
        function g(b, c, d, e) {
            return c = a.document.createElement(c),
            i(c, {
                visibility: "hidden",
                color: d
            }),
            b.appendChild(c),
            d = e(c),
            b.removeChild(c),
            d
        }
        function h(b, d) {
            d = d || {};
            var f = d.container || a.document.body;
            return a.getComputedStyle ? (b = g(f, "span", b, function(b) {
                return a.getComputedStyle(b, null).getPropertyValue("color")
            }),
            e(c(b))) : (b = g(f, "textarea", b, function(a) {
                return a.createTextRange().queryCommandValue("ForeColor")
            }),
            {
                red: 255 & b,
                blue: b >>> 16,
                green: (65280 & b) >>> 8
            })
        }

        // add this START
        function oklchToRgb(oklchStr) {
            let match = oklchStr.match(/oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*\)/i);
            if (!match) {
                throw new Error("Invalid forma. Required 'oklch(L C H)'.");
            }

            let l = parseFloat(match[1]);
            let c = parseFloat(match[2]);
            let h = parseFloat(match[3]);

            let hr = (h * Math.PI) / 180;
            
            let a = c * Math.cos(hr);
            let b = c * Math.sin(hr);

            let l_ = l + 0.3963377774 * a + 0.2158037573 * b;
            let m_ = l - 0.1055613458 * a - 0.0638541728 * b;
            let s_ = l - 0.0894841775 * a - 1.2914855480 * b;

            let l3 = l_ ** 3;
            let m3 = m_ ** 3;
            let s3 = s_ ** 3;

            let red = 4.0767416621 * l3 - 3.3077115913 * m3 + 0.2309699292 * s3;
            let green = -1.2684380046 * l3 + 2.6097574011 * m3 - 0.3413193965 * s3;
            let bblue = -0.0041960863 * l3 - 0.7034186147 * m3 + 1.7076147010 * s3;

            function gammaCorrect(value) {
                return value <= 0.0031308
                    ? value * 12.92
                    : 1.055 * Math.pow(value, 1 / 2.4) - 0.055;
            }

            red = gammaCorrect(red);
            green = gammaCorrect(green);
            blue = gammaCorrect(bblue);

            red = Math.max(0, Math.min(255, Math.round(red * 255)));
            green = Math.max(0, Math.min(255, Math.round(green * 255)));
            bblue = Math.max(0, Math.min(255, Math.round(blue * 255)));

            return {red, green, blue};
        }
        // add this END

        var i = u;
        return function(a, b) {
            a = c(a);
            var g;
            if ("transparent" === a)
                return {
                    red: 0,
                    green: 0,
                    blue: 0,
                    alpha: 0
                };
            if ("#" === a.charAt(0))
                g = d;
            else if ("rgba(" === a.slice(0, 5))
                g = f;
            else if ("rgb(" === a.slice(0, 4))
                g = e;
            
            // add this START
            else if ("oklch(" === a.slice(0, 6))
                g = oklchToRgb;
            // add this END
            
            else {
                if (!/^[a-z]+$/.test(a))
                    throw new Error("parseColor received unparseable color: " + a);
                g = h
            }
            return g(a, b)
        }
    }

/// ....

```
```

**Comment by animanoir** [comment]
> I also experienced the same issue when using Disqus + daisyUI 4.7.0, and after I investigated, the cause was found to be in that latest version of daisyUI.
> 
> The temporary solution was that I used is using **daisyUI version 3.9.4**. After I downgraded, the error disappeared, but it should be noted that some features in daisyUI 4.7.0 stopped working. In my case, it wasn't a problem because I hadn't yet used the latest components from daisyUI.
> 
> Hope this helps.

I find horrible that just because a color we need to downgrade our whole system...

**Comment by JuanmanDev** [comment]
Hello! 
I find a workaround:

```javascript
// Save the original getComputedStyle function
const originalGetComputedStyle = window.getComputedStyle;

// Override getComputedStyle
window.getComputedStyle = function (element, pseudoElt) {
  const styles = originalGetComputedStyle(element, pseudoElt);

  // Return a proxy to intercept calls to getPropertyValue
  return new Proxy(styles, {
    get(target, prop) {
      if (prop === 'getPropertyValue') {
        return (property) => {
          const value = target.getPropertyValue(property);
          // Replace "oklch" values or handle them as needed
          if (value.includes('oklch')) {
            console.warn(`Property "${property}" contains "oklch", returning fallback value.`);
            return ''; // Return a fallback value
          }
          return value;
        };
      }
      return target[prop];
    },
  });
};
```

I have a similar problem on Nuxt disqus (Vue).
It's not perfect but it seems to fix the mayor problems.

I will write something about this on my blog in the future: https://juanman.tech/blog 
BTW: If you know how to custom the text colors let me know.

UPDATE: https://juanman.tech/blog/11

**Comment by JuanmanDev** [comment]
Sorry @LynxTR i would need a full environment to see where comes from and where is the error.
If you can share a netlify or vercel environment it would help.

In any case I recommend you to check what's going on and debug step by step where this errors come from 😊

**Comment by JuanmanDev** [comment]
Sorry @LynxTR i would need a full environment to see where comes from and where is the error.
If you can share a netlify or vercel environment it would help.

In any case I recommend you to check what's going on and debug step by step where this errors come from 😊

**Comment by qiweiii** [comment]
I also have this problem

to reproduce, you can simply create a latest next.js project from template locally and see global.css

```css
:root {
  --radius: 0.625rem;
  --background: oklch(1 0 0);
  --foreground: oklch(0.145 0 0);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.145 0 0);
  --popover: oklch(1 0 0);
  --popover-foreground: oklch(0.145 0 0);
  --primary: oklch(0.205 0 0);
  --primary-foreground: oklch(0.985 0 0);
  --secondary: oklch(0.97 0 0);
  --secondary-foreground: oklch(0.205 0 0);
  --muted: oklch(0.97 0 0);
  --muted-foreground: oklch(0.556 0 0);
  --accent: oklch(0.97 0 0);
  --accent-foreground: oklch(0.205 0 0);
  --destructive: oklch(0.577 0.245 27.325);
  --border: oklch(0.922 0 0);
  --input: oklch(0.922 0 0);
  --ring: oklch(0.708 0 0);
  --chart-1: oklch(0.646 0.222 41.116);
  --chart-2: oklch(0.6 0.118 184.704);
  --chart-3: oklch(0.398 0.07 227.392);
  --chart-4: oklch(0.828 0.189 84.429);
  --chart-5: oklch(0.769 0.188 70.08);
  --sidebar: oklch(0.985 0 0);
  --sidebar-foreground: oklch(0.145 0 0);
  --sidebar-primary: oklch(0.205 0 0);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.97 0 0);
  --sidebar-accent-foreground: oklch(0.205 0 0);
  --sidebar-border: oklch(0.922 0 0);
  --sidebar-ring: oklch(0.708 0 0);
}

.dark {
  --background: oklch(0.145 0 0);
  --foreground: oklch(0.985 0 0);
  --card: oklch(0.205 0 0);
  --card-foreground: oklch(0.985 0 0);
  --popover: oklch(0.205 0 0);
  --popover-foreground: oklch(0.985 0 0);
  --primary: oklch(0.922 0 0);
  --primary-foreground: oklch(0.205 0 0);
  --secondary: oklch(0.269 0 0);
  --secondary-foreground: oklch(0.985 0 0);
  --muted: oklch(0.269 0 0);
  --muted-foreground: oklch(0.708 0 0);
  --accent: oklch(0.269 0 0);
  --accent-foreground: oklch(0.985 0 0);
  --destructive: oklch(0.704 0.191 22.216);
  --border: oklch(1 0 0 / 10%);
  --input: oklch(1 0 0 / 15%);
  --ring: oklch(0.556 0 0);
  --chart-1: oklch(0.488 0.243 264.376);
  --chart-2: oklch(0.696 0.17 162.48);
  --chart-3: oklch(0.769 0.188 70.08);
  --chart-4: oklch(0.627 0.265 303.9);
  --chart-5: oklch(0.645 0.246 16.439);
  --sidebar: oklch(0.205 0 0);
  --sidebar-foreground: oklch(0.985 0 0);
  --sidebar-primary: oklch(0.488 0.243 264.376);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.269 0 0);
  --sidebar-accent-foreground: oklch(0.985 0 0);
  --sidebar-border: oklch(1 0 0 / 10%);
  --sidebar-ring: oklch(0.556 0 0);
}

```


with lots of `oklch`


Then use disqus-react component, you will be able to see this error
